name: Inspect

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Deps
        run: npm ci
      - name: Inspect
        run: npm run lint
